// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ea7a4bf2-5035-43f8-afaf-58f9814c53b5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_pk9eEjXnT",
    "aws_user_pools_web_client_id": "q6q3aircjdkr2cv71f9ktulac",
    "oauth": {}
};


export default awsmobile;
